apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: webapp
  namespace: argocd
  finalizers:
    - resources-finalizer.argocd.argoproj.io
spec:
  destination:
    name: ''
    namespace: default
    server: 'https://kubernetes.default.svc'
  source:
    path: webapp
    repoURL: 'https://github.com/rusita-cloud/webapp-config'
    targetRevision: master
  project: cicd
  syncPolicy:
    automated: null
    syncOptions:
      - CreateNamespace=true
